name: Godot Export and Release

# Trigger this workflow when a tag starting with 'v' is pushed
on:
  push:
    tags:
      - "v*.*.*" # Matches tags like v1.0.0, v1.2.3 etc.

permissions:
  contents: write # Needed to create releases and upload assets

jobs:
  export_and_release:
    name: Export and Release
    runs-on: ubuntu-latest # Use Linux runner

    strategy:
      matrix:
        # Define the export presets you want to build
        # These names MUST match the names in your export_presets.cfg
        preset: ["SplitSouls"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Godot
        uses: godotengine/godot-ci@v4
        with:
          godot-version: 4.4.1

      - name: Build Project - ${{ matrix.preset }}
        run: |
          mkdir -p build/${{ matrix.preset }}
          godot --headless --export-release "${{ matrix.preset }}" "build/${{ matrix.preset }}/SplitSouls" --verbose
          # Expects: build/Windows Desktop/SplitSouls.exe and build/Windows Desktop/SplitSouls.pck

      - name: Package Build - ${{ matrix.preset }}
        run: |
          cd build/${{ matrix.preset }} # Go into 'build/Windows Desktop'
          zip -r ../SplitSouls-${{ github.ref_name }}-Windows.zip SplitSouls.exe SplitSouls.pck # Zip contents into build/SplitSouls-TAG-Windows.zip
          cd ../.. # Go back to the project root

      - name: Upload Artifacts to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/SplitSouls-${{ github.ref_name }}-Windows.zip